services:
  mysql:
    image: mysql
    container_name: mysql_container
    environment:
      - MYSQL_DATABASE=rebu
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=${DBPASSWORD}
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    ports:
      - "3306:3306"
    volumes:
      - /home/ubuntu/data/db/mysql:/var/lib/mysql
    networks:
      - internal_network
  
  redis:
    image: redis
    container_name: redis_container
    ports:
      - "6379:6379"
    networks:
      - internal_network

  spring:
    build: ./back
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
    container_name: spring_container
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/rebu?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    networks:
      - internal_network
      
  jenkins:
    image: jenkins/jenkins:jdk17
    container_name: jenkins-container
    restart: always
    ports:
      - "7070:7070"
      - "50000:50000"
    environment:
      - JENKINS_OPTS=--httpPort=7070 --prefix=/jenkins
    volumes:
      - /home/ubuntu/data/jenkins:/var/jenkins_home
    networks:
      - internal_network
      
networks:
  internal_network: