services:
  rebu_mysql:
    image: mysql
    container_name: rebu_mysql_container
    environment:
      - MYSQL_DATABASE=rebu
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=${DBPASSWORD}
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    ports:
      - "3306:3306"
    volumes:
      - ~/rebu/database/mysql:/var/lib/mysql
    networks:
      - internal_network

  rebu_redis:
    image: redis
    container_name: rebu_redis_container
    ports:
      - "6379:6379"
    networks:
      - internal_network

  rebu_spring:
    build: ./back
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - rebu_mysql
      - rebu_redis
    container_name: rebu_spring_container
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://rebu_mysql:3306/rebu?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    networks:
      - internal_network

  rebu_jenkins:
    image: jenkins/jenkins:jdk17
    container_name: rebu_jenkins-container
    restart: always
    ports:
      - "7070:7070"
      - "50000:50000"
    environment:
      - JENKINS_OPTS=--httpPort=7070 --prefix=/jenkins
    volumes:
      - ~/rebu/deploy/jenkins:/var/jenkins_home
    networks:
      - internal_network

networks:
  internal_network: