spring:
  application:
    name: Rebu
  profiles:
    include: secret
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 100
      minimum-idle: 10
      idle-timeout: 600000
      max-lifetime: 1800000명
  #  sql:
  #    init:
  #      data-locations: classpath:data.sql
  #      encoding: UTF-8
  #      mode: always
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true
        default_batch_fetch_size: 1000
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
      enabled: true
  mustache:
    servlet:
      expose-request-attributes:

feed:
  cnt_image_max_limit: 5
  cnt_hashtag_max_limit: 5
  cnt_review_keyword_max_limit: 5
  storage_base_url: "/feeds"

server:
  servlet:
    session:
      timeout: 15m
