spring:
  application:
    name: Rebu
  profiles:
    include: secret
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#  sql:
#    init:
#      data-locations: classpath:data.sql
#      encoding: UTF-8
#      mode: always
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true
  data:
    redis:
      host: redis
      port: 6379