spring:
  application:
    name: Rebu
  profiles:
    include: secret
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#  sql:
#    init:
#      data-locations: classpath:data.sql
#      encoding: UTF-8
#      mode: always
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true
  data:
    redis:
      host: localhost
      port: 6379
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 10MB

feed:
  cnt_image_max_limit: 5
  cnt_hashtag_max_limit: 5
  storage_base_url: "/feeds"